name: Deploy Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build and test Bot
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          NODE_ENV: ${{ secrets.NODE_ENV || 'production' }}
          APP_ID: ${{secrets.APP_ID}}
          PUBLIC_KEY: ${{secrets.PUBLIC_KEY}}
          IPINFO_TOKEN: ${{secrets.IPINFO_TOKEN}}
          CLIENT_ID: ${{secrets.CLIENT_ID}}
        run: |
          npm run build
          npm run test